import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryProvider from "@/components/QueryProvider";
import Link from "next/link";
import WhoAmI from "@/components/WhoAmI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 text-gray-900 antialiased`}>
        <QueryProvider>
          <header className="border-b bg-white/90 backdrop-blur supports-[backdrop-filter]:bg-white/60 sticky top-0 z-40">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-10 flex items-center justify-between">
              <Link href="/" className="text-2xl font-semibold tracking-tight focus:outline-none focus:ring-2 focus:ring-black">IdeaBoard</Link>
              <nav className="flex items-center gap-6">
                <Link href="/" className="text-sm text-gray-700 hover:underline focus:outline-none focus:ring-2 focus:ring-black">Home</Link>
                <Link href="/new" className="text-sm text-gray-700 hover:underline focus:outline-none focus:ring-2 focus:ring-black">New</Link>
                <WhoAmI />
              </nav>
            </div>
          </header>
          <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
